# @package _group_


nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /ivi/ilps/personal/gsidiro/code/DPR/downloads/data/retriever_or/nq-train.json

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /ivi/ilps/personal/gsidiro/code/DPR/downloads/data/retriever_or/nq-dev.json

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test

curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test
